language: python
python:
  - '3.6'
addons:
  ssh_known_hosts: 84.201.163.97
script:
  - python -m unittest discover -s tests/ -p '*_tests.py'
before_install:
  - openssl aes-256-cbc -K $encrypted_d05f2b704764_key -iv $encrypted_d05f2b704764_iv
    -in .travis/deploy_key.enc -out /tmp/deploy_key -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - git remote add deploy ssh://entrant@84.201.163.97/home/entrant/git/yandex-academy-task.git/
  - git push deploy master
